apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-var-splunk-s1-standalone-0
  namespace: splunk-operator
  creationTimestamp: null
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef: 
    namespace: splunk-operator
    name: pvc-var-splunk-s1-standalone-0
  hostPath:
    path: /tmp
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-var-splunk-s1-standalone-0
  namespace: splunk-operator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
