apiVersion: v1
kind: Pod
metadata:
  name: elk-stack
spec:
  containers:
    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
      ports:
        - containerPort: 9200
    - name: logstash
      image: docker.elastic.co/logstash/logstash:7.14.0
      ports:
        - containerPort: 5044
    - name: kibana
      image: docker.elastic.co/kibana/kibana:7.14.0
      ports:
        - containerPort: 5601
