apiVersion: v1
kind: Pod
metadata:
  name: elk-stack
  labels:
    app: elk-stack
spec:
  containers:
    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
      resources:
        limits:
          memory: 2Gi
        requests:
          memory: 2Gi
      ports:
        - containerPort: 9200
    - name: logstash
      image: docker.elastic.co/logstash/logstash:8.8.2
      ports:
        - containerPort: 5044
    - name: kibana
      image: docker.elastic.co/kibana/kibana:8.8.2
      ports:
        - containerPort: 5601
