apiVersion: v1
kind: Pod
metadata:
  name: elk-stack
spec:
  containers:
    - name: logstash
      image: docker.elastic.co/logstash/logstash:8.8.2
      ports:
        - containerPort: 5044
    - name: kibana
      image: docker.elastic.co/kibana/kibana:8.8.2
      ports:
        - containerPort: 5601
